source $stdenv/setup

mkdir -p $out
cd $out

mkdir -p $(dirname $packageName)

ln -sf $package $packageName

for binNameAndPath in $binNameAndPaths; do
  mkdir -p "$out/bin"
  IFS='|' read -r -a arr <<< "$binNameAndPath"
  binName=${arr[0]}
  sourcePath=${arr[1]}

  {
    echo "#!$bash/bin/bash"
    echo "#"
    echo "# $binName"
    echo "# This binstub is generated by mkNodePackageWithRuntime."
    echo ""
    echo "source '$envSetupScript'"
    echo "\"\$(\"$coreutils/bin/dirname\" \$(\"$coreutils/bin/realpath\" \"\$0\"))/../$sourcePath\" \"\$@\""
  } > "$out/bin/$binName"
  chmod +x "$out/bin/$binName"
done
